In [1]:
# Run this first, then restart runtime :)

!pip install auto-sklearn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 4.0 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached typing_extensions-4.8.0-py3-none-any.whl.metadata (3.0 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 4.2 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1392 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
      <string>:116: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of 

In [2]:
import autosklearn

ModuleNotFoundError: ignored

In [ ]:
import pandas as pd

df = pd.read_csv('housing.csv')

df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
target = df.pop('median_house_value')
df = pd.concat([df, target], axis=1)

df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0       322.0       126.0         8.3252        NEAR BAY            452600.0  
1      2401.0      1138.0         8.3014        NEAR BAY            358500.0  
2       496.0       177.0         7.2574        NEAR BAY            352100.0  
3       558.0       219.0         5.6431        NEAR BAY            341300.0  
4       565.0       259.0         3.8462        NEAR BAY            342200.0

In [ ]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
ocean_proximity        object
median_house_value    float64
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['ocean_proximity'] = le.fit_transform(df['ocean_proximity'])

df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  ocean_proximity  \
0           322.0       126.0         8.3252                3   
1          2401.0      1138.0         8.3014                3   
2           496.0       177.0         7.2574                3   
3           558.0       219.0         5.6431                3   
4           565.0       259.0         3.8462                3   
...           ...         ...            ...              ...   
20635       845.0       330.0         1.5603                1   
20636       356.0       114.0         2.5568                1   
20637      1007.0       433.0         1.7000                1   
20638       741.0       349.0         1.8672                1   
20639      1387.0       530.0         2.3886                1   

       median_house_value  
0                452600.0  
1                358500.0  
2                352100.0  
3                341300.0  
4                342200.0  
...                   ...  
20635             78100.0  
20636             77100.0  
20637             92300.0  
20638             84700.0  
20639             89400.0  

[20640 rows x 10 columns]

In [ ]:
df = df.sample(frac=1, random_state=0)
df.reset_index(drop=True, inplace=True)

split_index = int(len(df) * 0.75)

train_df = df[:split_index]
test_df = df[split_index:]

train_df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -117.05     32.58                22.0       2101.0           399.0   
1    -117.97     33.92                32.0       2620.0           398.0   
2    -121.84     38.65                29.0       3167.0           548.0   
3    -115.60     33.20                37.0        709.0           187.0   
4    -122.43     37.79                25.0       1637.0           394.0   

   population  households  median_income  ocean_proximity  median_house_value  
0      1551.0       371.0         4.1518                4            136900.0  
1      1296.0       429.0         5.7796                0            241300.0  
2      1554.0       534.0         4.3487                1            200700.0  
3       390.0       142.0         2.4511                1             72500.0  
4       649.0       379.0         5.0049                3            460000.0

In [ ]:
X_train = train_df.to_numpy()[:, :-1]
y_train = train_df.to_numpy()[:, -1]

X_test = test_df.to_numpy()[:, :-1]
y_test = test_df.to_numpy()[:, -1]

(X_train.shape, y_train.shape), (X_test.shape, y_test.shape)

(((15480, 9), (15480,)), ((5160, 9), (5160,)))

In [ ]:
feature_types = ['Numerical']*8 + ['Categorical']

feature_types

['Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Numerical',
 'Categorical']

In [ ]:
import autosklearn.regression

autosklearn_regressor = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=240,
    per_run_time_limit=60,
)

autosklearn_regressor.fit(X_train, y_train, feat_type=feature_types)

AutoSklearnRegressor(per_run_time_limit=60, time_left_for_this_task=240)

In [ ]:
print(autosklearn_regressor.leaderboard())

          rank  ensemble_weight               type      cost   duration
model_id                                                               
7            1              0.4  gradient_boosting  0.170498   6.286444
4            2              0.2  gradient_boosting  0.171715  31.349281
5            3              0.3  gradient_boosting  0.174482  51.902443
8            4              0.1  gradient_boosting  0.183270   4.682676


In [ ]:
from sklearn.metrics import mean_absolute_error as mae

mae(y_train, autosklearn_regressor.predict(X_train)), mae(y_test, autosklearn_regressor.predict(X_test))

(18471.02661000333, 29713.159015223777)

In [ ]:
autosklearn_regressor.predict(X_train)

array([133374.36816406, 247729.1171875 , 174224.28222656, ...,
       178951.796875  , 114125.41601562, 147027.92675781])

In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

X2, y2 = iris.data, iris.target

X2.shape, y2.shape

((150, 4), (150,))

In [ ]:
y2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.4, random_state=1)

X_train2.shape, y_train2.shape, X_test2.shape, y_test2.shape

((90, 4), (90,), (60, 4), (60,))

In [ ]:
import autosklearn.classification

autosklearn_classifier = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=80,
    per_run_time_limit=20,
)

autosklearn_classifier.fit(X_train2, y_train2)

[WARNING] [2022-05-08 22:42:32,534:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-05-08 22:42:39,650:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-05-08 22:42:45,910:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-05-08 22:42:47,775:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.


AutoSklearnClassifier(per_run_time_limit=20, time_left_for_this_task=80)

In [ ]:
print(autosklearn_classifier.leaderboard())

          rank  ensemble_weight                type      cost  duration
model_id                                                               
2            1             0.06       random_forest  0.000000  1.884154
25           2             0.04       random_forest  0.000000  2.229381
24           3             0.08   gradient_boosting  0.000000  1.715485
21           4             0.06         extra_trees  0.000000  1.830233
19           5             0.04       random_forest  0.000000  1.921622
14           6             0.02       random_forest  0.000000  1.815338
12           7             0.06                 mlp  0.000000  2.221534
29           8             0.06         gaussian_nb  0.000000  1.166276
10           9             0.02                 mlp  0.000000  1.754310
6           10             0.04          libsvm_svc  0.000000  0.894585
16          11             0.06            adaboost  0.033333  1.858236
27          12             0.02       random_forest  0.033333  2

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_train2,
                           autosklearn_classifier.predict(X_train2)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      0.97      0.98        29
           2       0.97      1.00      0.98        30

    accuracy                           0.99        90
   macro avg       0.99      0.99      0.99        90
weighted avg       0.99      0.99      0.99        90



In [ ]:
print(classification_report(y_test2,
                           autosklearn_classifier.predict(X_test2)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.95      0.95      0.95        21
           2       0.95      0.95      0.95        20

    accuracy                           0.97        60
   macro avg       0.97      0.97      0.97        60
weighted avg       0.97      0.97      0.97        60



In [ ]:
autosklearn_classifier.predict(X_test2)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])